before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - main: ./
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
    targets:
      - linux_amd64
    binary: '{{ .ProjectName }}'

  - main: ./cli
    id: 'nmctl'
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    binary: 'nmctl'
archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'
release:
  prerelease: true
    
